/// Cross-version compatibility test.
/// Verifies NEW deps (curve25519-dalek 4, x25519-dalek 2, sha2 0.10, hmac 0.12)
/// can decrypt data encrypted by OLD deps (curve25519-dalek 3, x25519-dalek 1, sha2 0.9, hmac 0.11).
use uniffi_dtproto::{DTProto, DTCurve, IdentityVerifyResult};
use std::collections::HashMap;

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}
fn from_hex(s: &str) -> Vec<u8> {
    (0..s.len()).step_by(2).map(|i| u8::from_str_radix(&s[i..i+2], 16).unwrap()).collect()
}

fn alice_pri() -> Vec<u8> { from_hex("c806439dc9d2c476ffed8f2580c0888d58ab406bf7ae3698879021b96bb4bf59") }
fn alice_pub() -> Vec<u8> { from_hex("1bb75966f2e93a3691dfff942bb2a466a1c08b8d78ca3f4d6df8b8bfa2e4ee28") }
fn bob_pri() -> Vec<u8>  { from_hex("b03b34c33a1c44f225b662d2bf4859b8135411fa7b0386d45fb75dc5b91b4466") }
fn bob_pub() -> Vec<u8>  { from_hex("653614993d2b15ee9e5fd3d86ce719ef4ec1daae1886a87b3f5fa9565a27a22f") }

// =====================================================================
// Data encrypted by OLD version (curve25519-dalek 3, x25519-dalek 1)
// Generated by running cross_version_gen with old deps
// =====================================================================
const OLD_MSG_CIPHER_TEXT: &str  = "2c99a77949244d9f0df802f14104253b13973b4079be2ead0d9a656bd5f4d17ff3885aa39672e6768fa6b6b6b57071";
const OLD_MSG_SIGNED_E_KEY: &str = "509b57cb18b5da57f5328c0eb0005abff1e753578e7070c16af5bb3ee2d806c831b1c60b568221527af6427fd1498518fb25bcaf932ae42dcbddd51e6bd5ef00";
const OLD_MSG_E_KEY: &str        = "6577bed6948c4f8d23096a48d9f5e7b37e2757b730568c94ad98d4225f47a53f";
const OLD_MSG_IDENTITY_KEY: &str = "653614993d2b15ee9e5fd3d86ce719ef4ec1daae1886a87b3f5fa9565a27a22f";

const OLD_RTM_CIPHER_TEXT: &str = "c1748c77707ac25a9b28179e69bb8157df6d0087addbcf694e8d252588af32bcdee0edf92bd6b2af7bc2b129";
const OLD_RTM_SIGNATURE: &str   = "2f387648f301097fe8e68f4ba53513a5feedaab5129aa573f1eb9bc4f84eb0638a0ace27f24ac9b8a6433c91c9a0b09e8b595013348793b2d60cb69e42fb6d03";

const OLD_KEY_M_KEY: &str          = "e4d5aadfab1aa3f5863408092dac0045c790851d65ecf6dca106151c90298bfdb12d7f5e2d1ce6623c7c6831e65993031014aacb6f26cacae856943a181e188c";
const OLD_KEY_E_KEY: &str          = "0362f5c03bc180ce027eae6e91f5828d7b08323e548f7c9d3629e00b8fc7c936";
const OLD_KEY_E_M_KEY_ALICE: &str  = "ed15a4bc2786c61614b80a157dec1819eb36ac1e320c9cb57bc794bd69e4fdbcfe2e583be639d4ea62ef15af5c2d82150e59363f3ca3bc31cd3a7de4fb88503bd5648a9b1822bdc325d44e06440bf4c175a68cb39228c7e6fa442a02";

// =====================================================================
// Test 1: DH shared secrets must be identical
// =====================================================================
#[test]
fn dh_shared_secret_v1_matches_old() {
    let curve = DTCurve;
    let alice_pub_arr: [u8; 32] = alice_pub().try_into().unwrap();
    let bob_pri_arr: [u8; 32] = bob_pri().try_into().unwrap();

    let shared = curve.dhe_key_agreement(&alice_pub_arr, &bob_pri_arr, 1);
    assert_eq!(hex(&shared), "325f239328941ced6e673b86ba41017448e99b649a9c3806c1dd7ca4c477e629",
        "V1 (raw DH) shared secret mismatch!");
}

#[test]
fn dh_shared_secret_v3_matches_old() {
    let curve = DTCurve;
    let alice_pub_arr: [u8; 32] = alice_pub().try_into().unwrap();
    let bob_pri_arr: [u8; 32] = bob_pri().try_into().unwrap();

    let shared = curve.dhe_key_agreement(&alice_pub_arr, &bob_pri_arr, 3);
    assert_eq!(hex(&shared), "e90016ebdd3ff3d04404ef01db3662609fd9cf56cdd57b27cd2ad30188540c0e",
        "V3 (HKDF) shared secret mismatch!");
}

// =====================================================================
// Test 2: Public key derivation must be identical
// =====================================================================
#[test]
fn public_key_derivation_matches_old() {
    let curve = DTCurve;
    let bob_key = curve.from_key(&bob_pri().try_into().unwrap());
    assert_eq!(hex(&bob_key.derive_public_key_bytes()), "653614993d2b15ee9e5fd3d86ce719ef4ec1daae1886a87b3f5fa9565a27a22f",
        "Bob public key derivation mismatch!");

    let alice_key = curve.from_key(&alice_pri().try_into().unwrap());
    assert_eq!(hex(&alice_key.derive_public_key_bytes()), "1bb75966f2e93a3691dfff942bb2a466a1c08b8d78ca3f4d6df8b8bfa2e4ee28",
        "Alice public key derivation mismatch!");
}

// =====================================================================
// Test 3: NEW code decrypts OLD private chat message
// =====================================================================
#[test]
fn decrypt_old_private_message() {
    let proto = DTProto::new(1); // old version used v1 (raw DH)

    let decrypted = proto.decrypt_message(
        from_hex(OLD_MSG_SIGNED_E_KEY),
        from_hex(OLD_MSG_IDENTITY_KEY),
        from_hex(OLD_MSG_IDENTITY_KEY),
        Some(from_hex(OLD_MSG_IDENTITY_KEY)),
        from_hex(OLD_MSG_E_KEY),
        alice_pri(),
        Vec::new(),
        from_hex(OLD_MSG_CIPHER_TEXT),
    ).expect("Failed to decrypt old-version message with new deps!");

    assert_eq!(String::from_utf8(decrypted.plain_text).unwrap(), "hello cross version");
    assert!(matches!(decrypted.identity_verify_result, IdentityVerifyResult::Match));
}

// =====================================================================
// Test 4: NEW code decrypts OLD RTM message + verifies signature
// =====================================================================
#[test]
fn decrypt_old_rtm_message() {
    let aes_key = vec![0x42u8; 32]; // same fixed key used during encryption
    let proto = DTProto::new(1);

    let decrypted = proto.decrypt_rtm_message(
        from_hex(OLD_RTM_SIGNATURE),
        Some(bob_pub()),
        aes_key,
        from_hex(OLD_RTM_CIPHER_TEXT),
    ).expect("Failed to decrypt old-version RTM message with new deps!");

    assert_eq!(String::from_utf8(decrypted.plain_text).unwrap(), "hello rtm compat");
    assert!(decrypted.verified_id_result, "Signature verification failed for old RTM message!");
}

// =====================================================================
// Test 5: NEW code decrypts OLD encrypted key
// =====================================================================
#[test]
fn decrypt_old_encrypted_key() {
    let proto = DTProto::new(1);

    let decrypted = proto.decrypt_key(
        from_hex(OLD_KEY_E_KEY),
        alice_pri(),
        from_hex(OLD_KEY_E_M_KEY_ALICE),
    ).expect("Failed to decrypt old-version encrypted key with new deps!");

    assert_eq!(hex(&decrypted.m_key), OLD_KEY_M_KEY,
        "Decrypted key doesn't match original!");
}

// =====================================================================
// Test 6: XEdDSA signature from Signal test vectors (produced by dalek 3)
// =====================================================================
#[test]
fn verify_signal_test_vector_signature() {
    let alice_identity_public: [u8; 32] = [
        0xab,0x7e,0x71,0x7d,0x4a,0x16,0x3b,0x7d,0x9a,0x1d,0x80,0x71,0xdf,0xe9,
        0xdc,0xf8,0xcd,0xcd,0x1c,0xea,0x33,0x39,0xb6,0x35,0x6b,0xe8,0x4d,0x88,
        0x7e,0x32,0x2c,0x64,
    ];
    let alice_ephemeral_public: [u8; 33] = [
        0x05,0xed,0xce,0x9d,0x9c,0x41,0x5c,0xa7,0x8c,0xb7,0x25,0x2e,0x72,0xc2,
        0xc4,0xa5,0x54,0xd3,0xeb,0x29,0x48,0x5a,0x0e,0x1d,0x50,0x31,0x18,0xd1,
        0xa8,0x2d,0x99,0xfb,0x4a,
    ];
    let alice_signature: [u8; 64] = [
        0x5d,0xe8,0x8c,0xa9,0xa8,0x9b,0x4a,0x11,0x5d,0xa7,0x91,0x09,0xc6,0x7c,
        0x9c,0x74,0x64,0xa3,0xe4,0x18,0x02,0x74,0xf1,0xcb,0x8c,0x63,0xc2,0x98,
        0x4e,0x28,0x6d,0xfb,0xed,0xe8,0x2d,0xeb,0x9d,0xcd,0x9f,0xae,0x0b,0xfb,
        0xb8,0x21,0x56,0x9b,0x3d,0x90,0x01,0xbd,0x81,0x30,0xcd,0x11,0xd4,0x86,
        0xce,0xf0,0x47,0xbd,0x60,0xb8,0x6e,0x88,
    ];

    let curve = DTCurve;
    assert!(curve.verify_signature(&alice_identity_public, &alice_ephemeral_public, &alice_signature),
        "Signal XEdDSA test vector signature failed to verify with new deps!");
}

// =====================================================================
// Test 7: v1/v2/v3 encrypt-decrypt round trip with production-style keys
// =====================================================================
#[test]
fn all_versions_round_trip() {
    for version in [1, 2, 3] {
        let proto = DTProto::new(version);
        for i in 0..10 {
            let msg = format!("v{} round trip #{}", version, i);
            let encrypted = proto.encrypt_message(
                alice_pub(), HashMap::new(), bob_pri(), msg.as_bytes().to_vec(),
            ).unwrap();

            let decrypted = proto.decrypt_message(
                encrypted.signed_e_key, encrypted.identity_key.clone(),
                encrypted.identity_key.clone(), Some(encrypted.identity_key),
                encrypted.e_key, alice_pri(), Vec::new(), encrypted.cipher_text,
            ).unwrap();

            assert_eq!(String::from_utf8(decrypted.plain_text).unwrap(), msg);
            assert!(matches!(decrypted.identity_verify_result, IdentityVerifyResult::Match));
        }
    }
}
