// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(dtprotoFFI)
import dtprotoFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_dtproto_4da2_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_dtproto_4da2_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: {
        $0.deallocate()
        return UniffiInternalError.unexpectedRustCallError
    })
}

private func rustCallWithError<T, F: FfiConverter>
    (_ errorFfiConverter: F.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T
    where F.SwiftType: Error, F.FfiType == RustBuffer
    {
    try makeRustCall(callback, errorHandler: { return try errorFfiConverter.lift($0) })
}

private func makeRustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T, errorHandler: (RustBuffer) throws -> Error) throws -> T {
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    switch callStatus.code {
        case CALL_SUCCESS:
            return returnedVal

        case CALL_ERROR:
            throw try errorHandler(callStatus.errorBuf)

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public protocol DTProtoProtocol {
    func `decryptMessage`(`sessionId`: String, `signedEKey`: [UInt8], `theirIdKey`: [UInt8], `localTheirIdKey`: [UInt8], `cachedTheirIdKey`: [UInt8]?, `eKey`: [UInt8], `localPriKey`: [UInt8], `ermKey`: [UInt8], `cipherText`: [UInt8]) throws -> DtDecryptedMessage
    func `encryptMessage`(`sessionId`: String, `pubIdKey`: [UInt8], `pubIdKeys`: [String: [UInt8]], `localPriKey`: [UInt8], `plainText`: [UInt8]) throws -> DtEncryptedMessage
    func `decryptKey`(`eKey`: [UInt8], `localPriKey`: [UInt8], `eMKey`: [UInt8]) throws -> DtDecryptedKey
    func `encryptKey`(`pubIdKeys`: [String: [UInt8]], `mKey`: [UInt8]?) throws -> DtEncryptedKey
    func `generateKey`()  -> [UInt8]
    func `decryptRtmMessage`(`signature`: [UInt8], `theirLocalIdKey`: [UInt8]?, `aesKey`: [UInt8], `cipherText`: [UInt8]) throws -> DtDecryptedRtmMessage
    func `encryptRtmMessage`(`aesKey`: [UInt8], `localPriKey`: [UInt8], `plainText`: [UInt8]) throws -> DtEncryptedRtmMessage
    
}

public class DtProto: DTProtoProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }
    public convenience init(`version`: Int32)  {
        self.init(unsafeFromRawPointer: try!
    
    rustCall() {
    
    dtproto_4da2_DTProto_new(
        FfiConverterInt32.lower(`version`), $0)
})
    }

    deinit {
        try! rustCall { ffi_dtproto_4da2_DTProto_object_free(pointer, $0) }
    }

    

    
    public func `decryptMessage`(`sessionId`: String, `signedEKey`: [UInt8], `theirIdKey`: [UInt8], `localTheirIdKey`: [UInt8], `cachedTheirIdKey`: [UInt8]?, `eKey`: [UInt8], `localPriKey`: [UInt8], `ermKey`: [UInt8], `cipherText`: [UInt8]) throws -> DtDecryptedMessage {
        return try FfiConverterTypeDtDecryptedMessage.lift(
            try
    rustCallWithError(FfiConverterTypeDtProtoError.self) {
    dtproto_4da2_DTProto_decrypt_message(self.pointer, 
        FfiConverterString.lower(`sessionId`), 
        FfiConverterSequenceUInt8.lower(`signedEKey`), 
        FfiConverterSequenceUInt8.lower(`theirIdKey`), 
        FfiConverterSequenceUInt8.lower(`localTheirIdKey`), 
        FfiConverterOptionSequenceUInt8.lower(`cachedTheirIdKey`), 
        FfiConverterSequenceUInt8.lower(`eKey`), 
        FfiConverterSequenceUInt8.lower(`localPriKey`), 
        FfiConverterSequenceUInt8.lower(`ermKey`), 
        FfiConverterSequenceUInt8.lower(`cipherText`), $0
    )
}
        )
    }
    public func `encryptMessage`(`sessionId`: String, `pubIdKey`: [UInt8], `pubIdKeys`: [String: [UInt8]], `localPriKey`: [UInt8], `plainText`: [UInt8]) throws -> DtEncryptedMessage {
        return try FfiConverterTypeDtEncryptedMessage.lift(
            try
    rustCallWithError(FfiConverterTypeDtProtoError.self) {
    dtproto_4da2_DTProto_encrypt_message(self.pointer, 
        FfiConverterString.lower(`sessionId`), 
        FfiConverterSequenceUInt8.lower(`pubIdKey`), 
        FfiConverterDictionaryStringSequenceUInt8.lower(`pubIdKeys`), 
        FfiConverterSequenceUInt8.lower(`localPriKey`), 
        FfiConverterSequenceUInt8.lower(`plainText`), $0
    )
}
        )
    }
    public func `decryptKey`(`eKey`: [UInt8], `localPriKey`: [UInt8], `eMKey`: [UInt8]) throws -> DtDecryptedKey {
        return try FfiConverterTypeDtDecryptedKey.lift(
            try
    rustCallWithError(FfiConverterTypeDtProtoError.self) {
    dtproto_4da2_DTProto_decrypt_key(self.pointer, 
        FfiConverterSequenceUInt8.lower(`eKey`), 
        FfiConverterSequenceUInt8.lower(`localPriKey`), 
        FfiConverterSequenceUInt8.lower(`eMKey`), $0
    )
}
        )
    }
    public func `encryptKey`(`pubIdKeys`: [String: [UInt8]], `mKey`: [UInt8]?) throws -> DtEncryptedKey {
        return try FfiConverterTypeDtEncryptedKey.lift(
            try
    rustCallWithError(FfiConverterTypeDtProtoError.self) {
    dtproto_4da2_DTProto_encrypt_key(self.pointer, 
        FfiConverterDictionaryStringSequenceUInt8.lower(`pubIdKeys`), 
        FfiConverterOptionSequenceUInt8.lower(`mKey`), $0
    )
}
        )
    }
    public func `generateKey`()  -> [UInt8] {
        return try! FfiConverterSequenceUInt8.lift(
            try!
    rustCall() {
    
    dtproto_4da2_DTProto_generate_key(self.pointer, $0
    )
}
        )
    }
    public func `decryptRtmMessage`(`signature`: [UInt8], `theirLocalIdKey`: [UInt8]?, `aesKey`: [UInt8], `cipherText`: [UInt8]) throws -> DtDecryptedRtmMessage {
        return try FfiConverterTypeDtDecryptedRtmMessage.lift(
            try
    rustCallWithError(FfiConverterTypeDtProtoError.self) {
    dtproto_4da2_DTProto_decrypt_rtm_message(self.pointer, 
        FfiConverterSequenceUInt8.lower(`signature`), 
        FfiConverterOptionSequenceUInt8.lower(`theirLocalIdKey`), 
        FfiConverterSequenceUInt8.lower(`aesKey`), 
        FfiConverterSequenceUInt8.lower(`cipherText`), $0
    )
}
        )
    }
    public func `encryptRtmMessage`(`aesKey`: [UInt8], `localPriKey`: [UInt8], `plainText`: [UInt8]) throws -> DtEncryptedRtmMessage {
        return try FfiConverterTypeDtEncryptedRtmMessage.lift(
            try
    rustCallWithError(FfiConverterTypeDtProtoError.self) {
    dtproto_4da2_DTProto_encrypt_rtm_message(self.pointer, 
        FfiConverterSequenceUInt8.lower(`aesKey`), 
        FfiConverterSequenceUInt8.lower(`localPriKey`), 
        FfiConverterSequenceUInt8.lower(`plainText`), $0
    )
}
        )
    }
    
}


public struct FfiConverterTypeDtProto: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = DtProto

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtProto {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: DtProto, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> DtProto {
        return DtProto(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: DtProto) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}


public struct DtDecryptedKey {
    public var `mKey`: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`mKey`: [UInt8]) {
        self.`mKey` = `mKey`
    }
}


extension DtDecryptedKey: Equatable, Hashable {
    public static func ==(lhs: DtDecryptedKey, rhs: DtDecryptedKey) -> Bool {
        if lhs.`mKey` != rhs.`mKey` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`mKey`)
    }
}


public struct FfiConverterTypeDtDecryptedKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtDecryptedKey {
        return try DtDecryptedKey(
            `mKey`: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: DtDecryptedKey, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.`mKey`, into: &buf)
    }
}


public func FfiConverterTypeDtDecryptedKey_lift(_ buf: RustBuffer) throws -> DtDecryptedKey {
    return try FfiConverterTypeDtDecryptedKey.lift(buf)
}

public func FfiConverterTypeDtDecryptedKey_lower(_ value: DtDecryptedKey) -> RustBuffer {
    return FfiConverterTypeDtDecryptedKey.lower(value)
}


public struct DtDecryptedMessage {
    public var `plainText`: [UInt8]
    public var `identityVerifyResult`: IdentityVerifyResult

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`plainText`: [UInt8], `identityVerifyResult`: IdentityVerifyResult) {
        self.`plainText` = `plainText`
        self.`identityVerifyResult` = `identityVerifyResult`
    }
}


extension DtDecryptedMessage: Equatable, Hashable {
    public static func ==(lhs: DtDecryptedMessage, rhs: DtDecryptedMessage) -> Bool {
        if lhs.`plainText` != rhs.`plainText` {
            return false
        }
        if lhs.`identityVerifyResult` != rhs.`identityVerifyResult` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`plainText`)
        hasher.combine(`identityVerifyResult`)
    }
}


public struct FfiConverterTypeDtDecryptedMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtDecryptedMessage {
        return try DtDecryptedMessage(
            `plainText`: FfiConverterSequenceUInt8.read(from: &buf), 
            `identityVerifyResult`: FfiConverterTypeIdentityVerifyResult.read(from: &buf)
        )
    }

    public static func write(_ value: DtDecryptedMessage, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.`plainText`, into: &buf)
        FfiConverterTypeIdentityVerifyResult.write(value.`identityVerifyResult`, into: &buf)
    }
}


public func FfiConverterTypeDtDecryptedMessage_lift(_ buf: RustBuffer) throws -> DtDecryptedMessage {
    return try FfiConverterTypeDtDecryptedMessage.lift(buf)
}

public func FfiConverterTypeDtDecryptedMessage_lower(_ value: DtDecryptedMessage) -> RustBuffer {
    return FfiConverterTypeDtDecryptedMessage.lower(value)
}


public struct DtDecryptedRtmMessage {
    public var `plainText`: [UInt8]
    public var `verifiedIdResult`: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`plainText`: [UInt8], `verifiedIdResult`: Bool) {
        self.`plainText` = `plainText`
        self.`verifiedIdResult` = `verifiedIdResult`
    }
}


extension DtDecryptedRtmMessage: Equatable, Hashable {
    public static func ==(lhs: DtDecryptedRtmMessage, rhs: DtDecryptedRtmMessage) -> Bool {
        if lhs.`plainText` != rhs.`plainText` {
            return false
        }
        if lhs.`verifiedIdResult` != rhs.`verifiedIdResult` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`plainText`)
        hasher.combine(`verifiedIdResult`)
    }
}


public struct FfiConverterTypeDtDecryptedRtmMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtDecryptedRtmMessage {
        return try DtDecryptedRtmMessage(
            `plainText`: FfiConverterSequenceUInt8.read(from: &buf), 
            `verifiedIdResult`: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DtDecryptedRtmMessage, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.`plainText`, into: &buf)
        FfiConverterBool.write(value.`verifiedIdResult`, into: &buf)
    }
}


public func FfiConverterTypeDtDecryptedRtmMessage_lift(_ buf: RustBuffer) throws -> DtDecryptedRtmMessage {
    return try FfiConverterTypeDtDecryptedRtmMessage.lift(buf)
}

public func FfiConverterTypeDtDecryptedRtmMessage_lower(_ value: DtDecryptedRtmMessage) -> RustBuffer {
    return FfiConverterTypeDtDecryptedRtmMessage.lower(value)
}


public struct DtEncryptedKey {
    public var `mKey`: [UInt8]
    public var `eMKeys`: [String: [UInt8]]
    public var `eKey`: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`mKey`: [UInt8], `eMKeys`: [String: [UInt8]], `eKey`: [UInt8]) {
        self.`mKey` = `mKey`
        self.`eMKeys` = `eMKeys`
        self.`eKey` = `eKey`
    }
}


extension DtEncryptedKey: Equatable, Hashable {
    public static func ==(lhs: DtEncryptedKey, rhs: DtEncryptedKey) -> Bool {
        if lhs.`mKey` != rhs.`mKey` {
            return false
        }
        if lhs.`eMKeys` != rhs.`eMKeys` {
            return false
        }
        if lhs.`eKey` != rhs.`eKey` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`mKey`)
        hasher.combine(`eMKeys`)
        hasher.combine(`eKey`)
    }
}


public struct FfiConverterTypeDtEncryptedKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtEncryptedKey {
        return try DtEncryptedKey(
            `mKey`: FfiConverterSequenceUInt8.read(from: &buf), 
            `eMKeys`: FfiConverterDictionaryStringSequenceUInt8.read(from: &buf), 
            `eKey`: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: DtEncryptedKey, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.`mKey`, into: &buf)
        FfiConverterDictionaryStringSequenceUInt8.write(value.`eMKeys`, into: &buf)
        FfiConverterSequenceUInt8.write(value.`eKey`, into: &buf)
    }
}


public func FfiConverterTypeDtEncryptedKey_lift(_ buf: RustBuffer) throws -> DtEncryptedKey {
    return try FfiConverterTypeDtEncryptedKey.lift(buf)
}

public func FfiConverterTypeDtEncryptedKey_lower(_ value: DtEncryptedKey) -> RustBuffer {
    return FfiConverterTypeDtEncryptedKey.lower(value)
}


public struct DtEncryptedMessage {
    public var `cipherText`: [UInt8]
    public var `signedEKey`: [UInt8]
    public var `eKey`: [UInt8]
    public var `identityKey`: [UInt8]
    public var `ermKeys`: [String: [UInt8]]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`cipherText`: [UInt8], `signedEKey`: [UInt8], `eKey`: [UInt8], `identityKey`: [UInt8], `ermKeys`: [String: [UInt8]]?) {
        self.`cipherText` = `cipherText`
        self.`signedEKey` = `signedEKey`
        self.`eKey` = `eKey`
        self.`identityKey` = `identityKey`
        self.`ermKeys` = `ermKeys`
    }
}


extension DtEncryptedMessage: Equatable, Hashable {
    public static func ==(lhs: DtEncryptedMessage, rhs: DtEncryptedMessage) -> Bool {
        if lhs.`cipherText` != rhs.`cipherText` {
            return false
        }
        if lhs.`signedEKey` != rhs.`signedEKey` {
            return false
        }
        if lhs.`eKey` != rhs.`eKey` {
            return false
        }
        if lhs.`identityKey` != rhs.`identityKey` {
            return false
        }
        if lhs.`ermKeys` != rhs.`ermKeys` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`cipherText`)
        hasher.combine(`signedEKey`)
        hasher.combine(`eKey`)
        hasher.combine(`identityKey`)
        hasher.combine(`ermKeys`)
    }
}


public struct FfiConverterTypeDtEncryptedMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtEncryptedMessage {
        return try DtEncryptedMessage(
            `cipherText`: FfiConverterSequenceUInt8.read(from: &buf), 
            `signedEKey`: FfiConverterSequenceUInt8.read(from: &buf), 
            `eKey`: FfiConverterSequenceUInt8.read(from: &buf), 
            `identityKey`: FfiConverterSequenceUInt8.read(from: &buf), 
            `ermKeys`: FfiConverterOptionDictionaryStringSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: DtEncryptedMessage, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.`cipherText`, into: &buf)
        FfiConverterSequenceUInt8.write(value.`signedEKey`, into: &buf)
        FfiConverterSequenceUInt8.write(value.`eKey`, into: &buf)
        FfiConverterSequenceUInt8.write(value.`identityKey`, into: &buf)
        FfiConverterOptionDictionaryStringSequenceUInt8.write(value.`ermKeys`, into: &buf)
    }
}


public func FfiConverterTypeDtEncryptedMessage_lift(_ buf: RustBuffer) throws -> DtEncryptedMessage {
    return try FfiConverterTypeDtEncryptedMessage.lift(buf)
}

public func FfiConverterTypeDtEncryptedMessage_lower(_ value: DtEncryptedMessage) -> RustBuffer {
    return FfiConverterTypeDtEncryptedMessage.lower(value)
}


public struct DtEncryptedRtmMessage {
    public var `cipherText`: [UInt8]
    public var `signature`: [UInt8]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(`cipherText`: [UInt8], `signature`: [UInt8]) {
        self.`cipherText` = `cipherText`
        self.`signature` = `signature`
    }
}


extension DtEncryptedRtmMessage: Equatable, Hashable {
    public static func ==(lhs: DtEncryptedRtmMessage, rhs: DtEncryptedRtmMessage) -> Bool {
        if lhs.`cipherText` != rhs.`cipherText` {
            return false
        }
        if lhs.`signature` != rhs.`signature` {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(`cipherText`)
        hasher.combine(`signature`)
    }
}


public struct FfiConverterTypeDtEncryptedRtmMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtEncryptedRtmMessage {
        return try DtEncryptedRtmMessage(
            `cipherText`: FfiConverterSequenceUInt8.read(from: &buf), 
            `signature`: FfiConverterSequenceUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: DtEncryptedRtmMessage, into buf: inout [UInt8]) {
        FfiConverterSequenceUInt8.write(value.`cipherText`, into: &buf)
        FfiConverterSequenceUInt8.write(value.`signature`, into: &buf)
    }
}


public func FfiConverterTypeDtEncryptedRtmMessage_lift(_ buf: RustBuffer) throws -> DtEncryptedRtmMessage {
    return try FfiConverterTypeDtEncryptedRtmMessage.lift(buf)
}

public func FfiConverterTypeDtEncryptedRtmMessage_lower(_ value: DtEncryptedRtmMessage) -> RustBuffer {
    return FfiConverterTypeDtEncryptedRtmMessage.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum IdentityVerifyResult {
    
    case `match`
    case `cacheOutdated`
    case `senderKeyUpdated`
    case `allMismatch`
}

public struct FfiConverterTypeIdentityVerifyResult: FfiConverterRustBuffer {
    typealias SwiftType = IdentityVerifyResult

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IdentityVerifyResult {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .`match`
        
        case 2: return .`cacheOutdated`
        
        case 3: return .`senderKeyUpdated`
        
        case 4: return .`allMismatch`
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IdentityVerifyResult, into buf: inout [UInt8]) {
        switch value {
        
        
        case .`match`:
            writeInt(&buf, Int32(1))
        
        
        case .`cacheOutdated`:
            writeInt(&buf, Int32(2))
        
        
        case .`senderKeyUpdated`:
            writeInt(&buf, Int32(3))
        
        
        case .`allMismatch`:
            writeInt(&buf, Int32(4))
        
        }
    }
}


public func FfiConverterTypeIdentityVerifyResult_lift(_ buf: RustBuffer) throws -> IdentityVerifyResult {
    return try FfiConverterTypeIdentityVerifyResult.lift(buf)
}

public func FfiConverterTypeIdentityVerifyResult_lower(_ value: IdentityVerifyResult) -> RustBuffer {
    return FfiConverterTypeIdentityVerifyResult.lower(value)
}


extension IdentityVerifyResult: Equatable, Hashable {}



public enum DtProtoError {

    
    
    // Simple error enums only carry a message
    case VersionError(message: String)
    
    // Simple error enums only carry a message
    case ParamsError(message: String)
    
    // Simple error enums only carry a message
    case VerifySignatureError(message: String)
    
    // Simple error enums only carry a message
    case KeyDataLengthError(message: String)
    
    // Simple error enums only carry a message
    case MessageDataLengthError(message: String)
    
    // Simple error enums only carry a message
    case EncryptMessageDataError(message: String)
    
    // Simple error enums only carry a message
    case DecryptMessageDataError(message: String)
    
}

public struct FfiConverterTypeDtProtoError: FfiConverterRustBuffer {
    typealias SwiftType = DtProtoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DtProtoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .VersionError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .ParamsError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .VerifySignatureError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .KeyDataLengthError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .MessageDataLengthError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .EncryptMessageDataError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .DecryptMessageDataError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DtProtoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case let .VersionError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
        case let .ParamsError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
        case let .VerifySignatureError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
        case let .KeyDataLengthError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
        case let .MessageDataLengthError(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
        case let .EncryptMessageDataError(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
        case let .DecryptMessageDataError(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)

        
        }
    }
}


extension DtProtoError: Equatable, Hashable {}

extension DtProtoError: Error { }

fileprivate struct FfiConverterOptionSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterOptionDictionaryStringSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [String: [UInt8]]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDictionaryStringSequenceUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDictionaryStringSequenceUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

fileprivate struct FfiConverterDictionaryStringSequenceUInt8: FfiConverterRustBuffer {
    public static func write(_ value: [String: [UInt8]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceUInt8.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [UInt8]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [UInt8]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceUInt8.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

public func `libName`()  -> String {
    return try! FfiConverterString.lift(
        try!
    
    rustCall() {
    
    dtproto_4da2_lib_name($0)
}
    )
}



/**
 * Top level initializers and tear down methods.
 *
 * This is generated by uniffi.
 */
public enum DtprotoLifecycle {
    /**
     * Initialize the FFI and Rust library. This should be only called once per application.
     */
    func initialize() {
    }
}